'use strict';

const { addTextproCommand } = require('./_shared');

addTextproCommand("dragonball", "/create-dragon-ball-style-text-effects-online-809.html", 1);
addTextproCommand("deadpool", "/create-text-effects-in-the-style-of-the-deadpool-logo-818.html", 2);
addTextproCommand("blackpink", "/create-a-blackpink-style-logo-with-members-signatures-810.html", 1);
addTextproCommand("neon1", "/blue-neon-text-effect-117.html", 1);
addTextproCommand("football", "/paul-scholes-shirt-foot-ball-335.html", 2);
addTextproCommand("steel", "/heated-steel-lettering-effect-65.html", 2);
addTextproCommand("paint", "/paint-splatter-text-effect-72.html", 1);
addTextproCommand("thunder", "/thunder-text-effect-online-97.html", 1);
addTextproCommand("thor", "/create-thor-logo-style-text-effects-online-for-free-796.html", 1);
addTextproCommand("graffiti1", "/cute-girl-painting-graffiti-text-effect-667.html", 2);
addTextproCommand("gold2", "/modern-gold-5-215.html", 1);
addTextproCommand("neon2", "/create-light-effects-green-neon-online-429.html", 1);
addTextproCommand("effacer", "/create-eraser-deleting-text-effect-online-717.html", 1);
addTextproCommand("galaxy", "/text-light-galaxy-effectt-345.html", 1);
addTextproCommand("logovintage", "/write-text-on-vintage-television-online-670.html", 1);
addTextproCommand("gold1", "/gold-text-effect-158.html", 1);
addTextproCommand("graffiti2", "/graffiti-text-5-180.html", 1);
addTextproCommand("hacker", "/create-anonymous-hacker-avatars-cyan-neon-677.html", 1);
addTextproCommand("rain", "/foggy-rainy-text-effect-75.html", 1);
addTextproCommand("typography", "/create-online-typography-art-effects-with-multiple-layers-811.html", 1);
addTextproCommand("gold3", "/glossy-chrome-text-effect-online-424.html", 1);
addTextproCommand("wood", "/create-3d-wood-text-effects-online-free-705.html", 2);
addTextproCommand("captain_america", "/create-a-cinematic-captain-america-text-effect-online-715.html", 2);
addTextproCommand("cubic", "/3d-cubic-text-effect-online-88.html", 1);
addTextproCommand("green_effect", "/create-unique-word-green-light-63.html", 1);
addTextproCommand("naruto", "/naruto-shippuden-logo-style-text-effect-online-808.html", 1);
addTextproCommand("sand", "/realistic-3d-sand-text-effect-online-580.html", 1);
addTextproCommand("plasma", "/plasma-text-effects-online-71.html", 1);
addTextproCommand("avengers", "/create-logo-3d-style-avengers-online-427.html", 2);
addTextproCommand("logounderwater", "/3d-underwater-text-effect-online-682.html", 1);
addTextproCommand("glass", "/write-text-on-wet-glass-online-589.html", 1);
addTextproCommand("graffiti3", "/cover-graffiti-181.html", 1);
addTextproCommand("summery", "/create-a-summery-sand-writing-text-effect-577.html", 1);
addTextproCommand("gold4", "/modern-gold-silver-210.html", 1);
addTextproCommand("cloud", "/cloud-text-effect-139.html", 1);
addTextproCommand("metal", "/metal-text-effect-online-110.html", 1);
addTextproCommand("watercolor", "/create-a-watercolor-text-effect-online-655.html", 1);
addTextproCommand("sci_fi", "/create-a-awesome-logo-sci-fi-effects-492.html", 2);
addTextproCommand("gold5", "/free-glitter-text-effect-maker-online-656.html", 2);
addTextproCommand("blackpink2", "/create-blackpink-s-born-pink-album-logo-online-779.html", 2);
addTextproCommand("cloud2", "/create-a-cloud-text-effect-in-the-sky-618.html", 1);
addTextproCommand("neon3", "/neon-text-effect-171.html", 1);
addTextproCommand("logospace", "/latest-space-3d-text-effect-online-559.html", 2);
addTextproCommand("boobs", "/music-equalizer-text-effect-259.html", 1);
addTextproCommand("blackpink3", "/create-a-blackpink-neon-logo-text-effect-online-710.html", 1);
addTextproCommand("onepiece", "/create-one-piece-facebook-cover-online-553.html", 1);
addTextproCommand("dragonball2", "/free-online-dragon-ball-facebook-cover-photos-maker-443.html", 1);
addTextproCommand("football2", "/text-on-shirt-club-real-madrid-267.html", 2);
addTextproCommand("football3", "/create-football-shirt-messi-barca-online-268.html");
addTextproCommand("futuris", "/light-text-effect-futuristic-technology-style-648.html", 1);
